Created basic outline for doubly linked list, with very basic tests
TreverArnold/data-structures pull request #3
Opened 2023-09-14 19:51 UTC by TreverArnold

2023-09-14 19:51 UTC, TreverArnold commented
(WIP)

2023-09-15 18:15 UTC, W-Ely requested changes
This seems very close.  I think your tests are a bit insufficient to know it's doing the right thing.  A few points to look at.

Class Names are always UpperCamelCase.

In the resting state of the linked list (not mid operation) the following should be true.
- The tail's .next should always be `None`.
- The head's prev should always be `None`.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +class doubly_LinkedList:
UpperCamelCase

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +        new_node.next = self.tail
Appending adds to the tail. Why would the new Node's next be the current tail?  Shouldn't it be the previous?

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +            self.tail.prev = None
What is the current value of new_node.previous? Why is line 25 needed here?

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +        self.head.prev = None
What is the current value of self.head.previous? Why is line 28 needed here?

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +            self.tail.next = self.head
Unclear to me why the .next of the tail would ever be anything but None?

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +        return value
I don't see any adjustment of the .tail here.  If you pop the last item from the list the tail should be `None`.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +            self.head.prev = None
The head's .prev should always be None and the tail's .next, so if all 4 are needed something is off here.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +            return
On a list 1 long, this would leave the tail with a node present.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list_test.py
> +    assert my_list._size == 3
You should check the the structure comprehensively on every step.  This means my_list.head.... should have it's values and pointer checked to.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list_test.py
> +    assert my_list._size == 1
Anytime you checkout a .next, a .previous or .previous.value should also be checked.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list_test.py
> +def test_doubly_linked_list_push():
I want to see all methods that manipulate the list, `push`, `pop`, `append`, `shift` to start at 0 or 3 long and go all the way the other direction with the structure comprehensively checked on each step.

Example:
```
dll = DoublyLinkedList([3,2,1])
assert dll.head.prev = None
assert dll.head.value = 1
assert dll.head.next.value = 2
assert dll.head.next.next.value = 3
assert dll.head.next.next.next = None
assert dll.tail.next = None
assert dll.tail.value = 3
assert dll.tail.prev.value = 2
assert dll.tail.prev.prev.value = 1
assert dll.tail.prev.prev.prev = None
assert dll._size = 3

assert dll.pop() == 1
assert dll.head.prev = None
assert dll.head.value = 2
assert dll.head.next.value = 3
assert dll.head.next.next = None
assert dll.tail.next = None
assert dll.tail.value = 3
assert dll.tail.prev.value = 2
assert dll.tail.prev.prev = None
assert dll._size = 2

assert dll.pop() == 2
assert dll.head.prev = None
assert dll.head.value = 3
assert dll.head.next = None
assert dll.tail.next = None
assert dll.tail.value = 3
assert dll.tail.prev = None
assert dll._size = 1

assert dll.pop() == 3
assert dll.head = None
assert dll.tail = None
assert dll._size = 0
```

I know this seems like a lot, but you'll see why it's import as you try to get the tests to pass.

2023-09-15 18:15 UTC, W-Ely commented on doubly_linked_list.py
> +            return
> remove(val) will remove the first instance of val found in the list, starting from the head. ...

If the list looked like head[a]<-->[b]<-->[c]<-->[b] and .remove(b) was called, the list should look like a - c - b not a - b - c.  Please write a test that covers this case.

2023-09-18 22:08 UTC, W-Ely reviewed
Looks great, one small thing.

2023-09-18 22:08 UTC, W-Ely commented on doubly_linked_list.py
> +        return self._size
Remove this method, it's not in the instructions.

2023-09-19 18:23 UTC, W-Ely approved these changes

2023-09-19 18:30 UTC, merged